### ISSUE TITLE
How to sync DefaultTimeSource's Elapsed

### ISSUE THREAD

**Issue by Caskia** [RobThree/IdGen#20]
I have two nodes writing records to database, using this component to generate the ids. But this ids' ordering is different from creationtime's, I think it's related to ```DefaultTimeSource```. I can not ensure this nodes start at same time, so the ```Stopwatch```'s ```Elapsed``` is different. How can I solve this problem? Remove the stopwatch's Elapsing? I don't know what it does.

**Comment by RobThree** [comment]
Which version are you using? (See #18)

The nodes aren't (usually) supposed to know about eachother; however: to synchronise their clocks you could/should use NTP.

**Comment by Caskia** [comment]
I have read this post #18  before.
version: 2.1.0

You can try this code:
```c#
var idGenerator1 = new IdGen.IdGenerator(10, new DateTime(2017, 12, 8, 0, 0, 0, DateTimeKind.Utc));

await Task.Delay(20 * 1000);
var idGenerator2 = new IdGen.IdGenerator(9, new DateTime(2017, 12, 8, 0, 0, 0, DateTimeKind.Utc));

var list = new List<(int, long)>();
list.Add((0, idGenerator1.CreateId()));
list.Add((1, idGenerator2.CreateId()));

await Task.Delay(1);

list.Add((2, idGenerator2.CreateId()));
await Task.Delay(5);
list.Add((3, idGenerator1.CreateId()));
```

the data in list index2  is always greater than index3

**Comment by RobThree** [comment]
Uh... you may have found a bug...

I'm currently looking into it. As a workaround, you may try this:

```c#
var ts = new DefaultTimeSource(new DateTime(2017, 12, 8, 0, 0, 0, DateTimeKind.Utc), TimeSpan.FromMilliseconds(1));
	
var idGenerator1 = new IdGen.IdGenerator(10, ts);
System.Threading.Thread.Sleep(20 * 1000);
var idGenerator2 = new IdGen.IdGenerator(9, ts);
```

This seems to ensure the same timesource is used.

**Comment by RobThree** [comment]
Hmm, ok, so here's a bit of undefined behaviour I hadn't thought about...

It took me a while to realize... Every IdGenerator shares the same, underlying, stopwatch which is used as a timesource. However, each IdGenerator gets it's own instance of a (Default)TimeSource. And _those_ stored, internally, an offset (when it is created) which was specific to the instance but should be shared among instances too.

In some perspective it's 'correct' behavior but I don't think it's very intuitive (hence your issue). So I've fixed it in 3935623 and will push an update to NuGet shortly.

**Comment by RobThree** [comment]
I have pushed [v2.2](https://www.nuget.org/packages/IdGen/2.2.0) to NuGet (~~may be a few minutes before it's available~~) should be available now. Please let me know if you still experience issues with this version.

Thanks for reporting this issue! 👍

**Comment by Caskia** [comment]
That's great, thank you for such a quick response, I will have a try.

**Comment by Caskia** [comment]
Why not use static constructor to start ```Stopwatch```? Every ```DefaultTimeSource``` instances will start ```Stopwatch```, although it will not have any impact.

**Comment by RobThree** [comment]
Because [CA1810: Initialize reference type static fields inline](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1810) 😉 
Yes, the stopwatch is 'started' (actually 'resumed') every new instance but, as you said, it doesn't have any impact.
If you have sound reasoning for moving to a static constructor I'm open for discussion 😉

**Comment by Caskia** [comment]
Thank you for giving me a lesson.

**Comment by RobThree** [comment]
You're welcome. But more importantly: Is your problem solved now? 😉

**Comment by Caskia** [comment]
it's solved 😄
