### ISSUE TITLE
Constructor mismatch

### ISSUE THREAD

**Issue by rubo** [RobThree/IdGen#25]
In the sample in README the `IdGenerator()` constructor takes 3 arguments, while in v3 it actually takes 2 -- `generatorId` and `options`. There's no argument for the epoch as shown in the sample. Either docs or the constructor needs to be updated.

**Comment by RobThree** [comment]
You are correct, I missed that one. I will correct the README (and SHFB file).

**Comment by RobThree** [comment]
And done. Thanks for bringing it to my attention!
