### ISSUE TITLE
IdGenerator.GetFromConfig("foo") is error!

### ISSUE THREAD

**Issue by BI7PRK** [RobThree/IdGen#3]
IdGenerator.GetFromConfig("foo") is error!

System.Configuration.ConfigurationErrorsException

**Comment by RobThree** [comment]
Did you add the section?
```xml
<configuration>
  <configSections>
    <section name="idGenSection" type="IdGen.Configuration.IdGeneratorsSection, IdGen" />
  </configSections>
  ...
</configuration>
```

Is your XML valid?

Please show your config if you don't want me to take wild guesses / stabs in the dark.

**Comment by BI7PRK** [comment]
XML config from doc demo
![default](https://cloud.githubusercontent.com/assets/24989210/24243359/d3840474-0ff5-11e7-8f71-cba061770b04.png)

**Comment by RobThree** [comment]
[configSections need to be the first element in `configuration`](https://msdn.microsoft.com/en-us/library/ms228256(v=vs.85).aspx):

> If the **configSections** element is in a configuration file, the **configSections** element must be the first child element of the **configuration** element.

Besides that, please work a little on your human-skills. The [initial issue](https://github.com/RobThree/IdGen/issues/3#issue-216373653) wasn't that great of a report to begin with and when a decent response comes you post [another 5 words and a screenshot](https://github.com/RobThree/IdGen/issues/3#issuecomment-288676139) (why a screenshot and not just the text?). Please have a look at this issue and try to stand in my (or other people's) shoes and see what you come across... "`<blablah>` is error! `<copy-paste exception>`" is *not* a decent bugreport. "XML config from doc demo `<dump screenshot>`" is *not* a decent reply. Starting with making decent, whole, sentences might be a good start 😉
