### ISSUE TITLE
Id to datetime

### ISSUE THREAD

**Issue by minhhungit** [RobThree/IdGen#31]
Hello, thank you, your library is very useful 

I have a question, can we get timestamp value from a ID , or can we know what Id value that start of each year ?

I am going to partition my table but I just have the Id value, I want to partition the table by year so I need to know what Id if start of a year

**Comment by RobThree** [comment]
See the [`FromID()`](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/IdGenerator.cs#L177) method which returns an [`ID`](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/ID.cs) structure.

**Comment by minhhungit** [comment]
thank you @RobThree , that anwsered my first question !

is there a way we can give generator any DateTime value and it will generate a ID for us, for example, if I give it timestamp 2030-01-01 00:00:00 then it will give me ID for the timestamp

**Comment by RobThree** [comment]
Pass an [`ITimeSource`](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/ITimeSource.cs) in the constructor via the [`IdGeneratorOptions`](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/IdGeneratorOptions.cs); you can use the [`DefaultTimeSource`](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/DefaultTimeSource.cs) if you don't want to implement your own and pass it a date to it's constructor.

**Comment by minhhungit** [comment]
@RobThree but ITimeSource define an Epoch , as I understand is the point start of IDs range

I have a fixed epoch, for example my epoch is 2020/01/01
I want to know what exactly ID value for a point in future, for example 2025/05/20 13:05:12
Everytime I give ID generator value `2025/05/20 13:05:12` I need it gives me back a fixed unique ID

ITimeSource is just help me define an epoch, not a point in future

**Comment by RobThree** [comment]
I'm not talking about an epoch <sub>(although, when you would use the [`DefaultTimeSource`](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/DefaultTimeSource.cs) you would need to 'misuse' the epoch for it - I only suggested it if this was a one-time thing or something)</sub>.

Simply implement an [`ITimeSource`](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/ITimeSource.cs) on which you can set the date to whatever you want. Give it a `SetTime()` method or something similar and you'll be able to set the time on your timesource to whatever you want.

**Comment by minhhungit** [comment]
But epoch is fixed, we don't change it. Sorry I am still confusing. I dont need to change it, if I change epoch then my Id will be changed based on the epoch then it is not correct anymore. ITimeSource just require epoch, it does not have another parameter for a Datetime that is for any day in future. I need two param for 2 datetime, one for epoch and one for a day in future

For example, I have epoch at 2020, at 2025 my ID = 5, at 2027 my Id = 10... (I dont want to change my epoch 2020, the epoch is fixed)
If I give the generator date 2025, I expect it will give me exactly ID = 5

**Comment by RobThree** [comment]
Forget about the epoch. What you want is an `ITimeSource` that you can 'force' to a specific date. So you implement an `ITimeSource`:

```c#
public class MyTimeSource : ITimeSource
{
    private static readonly TimeSpan _tickduration = TimeSpan.FromMilliseconds(1);
    public DateTimeOffset Epoch { get; private set; }
    public TimeSpan TickDuration => _tickduration;

    private DateTimeOffset _current;

    public MyTimeSource(DateTimeOffset? epoch = null)
    {
        Epoch = epoch ?? new DateTime(2020, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        _current = Epoch;
    }

    public void SetDateTime(DateTimeOffset dateTime) => _current = dateTime;
    public void Adjust(TimeSpan timeSpan) => _current = _current.Add(timeSpan);
    public long GetTicks() => (long)(_current - Epoch).TotalMilliseconds;
}
```

The above timesource has two methods: `SetDateTime()` which allows you to specify an exact date/time and `Adjust()` which allows you to "adjust" the current time of the timesource with a specified timespan to a later date*

Next, you tell IdGen to use your timesource and then you'll be able to 'set the clock' to whatever date/time you desire:

```c#
var mytimesource = new MyTimeSource();
var idgen = new IdGenerator(0, new IdGeneratorOptions(IdStructure.Default, mytimesource));

// Generate an ID
var id1 = idgen.CreateId();     // 0

// Set timesource to now
mytimesource.SetDateTime(DateTime.UtcNow);
var id2 = idgen.CreateId();     // 166125122225176576

// Set timesource to specific date
mytimesource.SetDateTime(new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc));
var id3 = idgen.CreateId();     // 662082630451200000

// Adjust timesource (+1 hour)
mytimesource.Adjust(TimeSpan.FromHours(1));
var id4 = idgen.CreateId();     // 662097729945600000
```

<sup>* Note that a specific IdGen instance will prevent you from setting the time 'backwards' to an earlier date; if you need to do that you'll need to create a new instance of the IdGen.</sup>

**Comment by minhhungit** [comment]
Many thanks @RobThree , the sample helps a lot, I understood

**Comment by minhhungit** [comment]
Thank you for your help, I've just bought you a coffee on p@ypal !

**Comment by RobThree** [comment]
That _really_ wasn't necessary but thank you very much! Much appreciated! 👊
