### ISSUE TITLE
Int use for Generator Id

### ISSUE THREAD

**Issue by fdhsdrdark** [RobThree/IdGen#32]
Just a quick question: The Generator Id is supposed to be 10 bits, however in the constructor(new IdGenerator(int myInt)) the passed in value - myInt, is 32 bits. Am I missing something?

Thank you very much,

**Comment by RobThree** [comment]
It's because we don't really have a 10-bit datatype in C# 😉 

Besides that, the Generator ID is _by default_ 10 bits but [could be anything](https://github.com/RobThree/IdGen#how-it-works) _up to_ 31 bits.

Also: have you tried passing in any value over 2<sup>#bits</sup>-1? You should see [an exception](https://github.com/RobThree/IdGen/blob/f634ad9eafa84f9ecee4f3ef693d0dd18f8c822f/IdGen/IdGenerator.cs#L65).

**Comment by fdhsdrdark** [comment]
Indeed you get an exception- just tried it, and indeed there is no 10-bit datatype! 
Ok, makes sense now. Thank you very much.

Kind Regards

**Comment by GeorgeMichalenas** [comment]
Hello, regarding the above question. We are trying to use the server Ip (stripped off the dots) as the generatorId value.

```
var timeSource = new TimeSource(0, TimeSpan.FromMilliseconds(1), DateTimeOffset.MinValue);
var structure = new IdStructure(22, 31, 10);
var generator = new IdGenerator(127001, new IdGeneratorOptions(structure, timeSource));
```

```
public class TimeSource : ITimeSource
{
	public long Current { get; private set; }
	public DateTimeOffset Epoch { get; private set; }
	public TimeSpan TickDuration { get; private set; }

	public TimeSource(long current, TimeSpan tickDuration, DateTimeOffset epoch)
	{
		Current = current;
		TickDuration = tickDuration;
		Epoch = epoch;
	}

	public long GetTicks()
	{
		return Current;
	}
}
```

When trying to execute the above, we are receiving an exception
"GeneratorId must be between 0 and 2147483647. (Parameter 'generatorId')"

but if we change the IdStructure value to (23, 30, 10) it will work but we will not be able to use the full range of IPs as a generatorId value.
Is there something we are missing?
Thank you very much.

**Comment by RobThree** [comment]
Let's not get into the fact of how an IP is correctly converted into 32 bits and why (23, 30, 10) will also not work. Let's focus on the fact why you would want to waste 32(!) bits on the generator id. Do you *really* have a need for 4.2 billion generators? Do you have 4.2 billion machines, threads, processes?

10 bits offers up to 1024 hosts, make it 11 and you're up to 2048 hosts. Each bit you add doubles the amount of generators but either costs you a bit in the timestamp part or a bit in the sequence part (either of which then consequently _halves_ in 'resolution'). I would start by thinking about coordinating your hosts/processes/threads in such a way that you don't need an IP address to rely on for generating a generator ID but something else. _There's_ your problem.

Depending on what your architecture is you may use a central service to "hand out" generator ID's, but you could just as well put the generator ID in the hosts' config or... anything really. Just don't waste 32 bits on something where 10, maybe 20 would suffice.

---

For what it's worth: to convert an IP-address into a 32 bit value you don't "strip off the dots" and stick the numbers together. That would result in 255.255.255.255 => 255255255255 worst case scenario, which doesn't fit in a (u)int by a long shot. Each of the octets (the numbers between the dots) are a byte. To convert an IP into a 32 bit value (say the IP 11.22.33.44) you need do to: 11 * 2<sup>^24</sup> + 22 * 2<sup>^16</sup> + 33 * 2<sup>^8</sup> + 44. Or use something like this:

```c#
public static uint IPAddressToUInt(IPAddress ip)
	=> (uint)IPAddress.NetworkToHostOrder(BitConverter.ToInt32(ip.GetAddressBytes(), 0));
```

Or:

```c#
public static int IPAddressToInt(IPAddress ip)
	=> IPAddress.NetworkToHostOrder(BitConverter.ToInt32(ip.GetAddressBytes(), 0));
```

**Comment by GeorgeMichalenas** [comment]
Thank you very much about the answer and especially the IP insights.
We will try indeed to use fewer bits in the configuration as you advised.
