### ISSUE TITLE
Duplicate Ids in a two instance microservice

### ISSUE THREAD

**Issue by dimitkos** [RobThree/IdGen#34]
Hello, I am using .Net 5 API and the nuget of the IdGen 3.0.0
**I am using two instances of this API**
In the logs, I noticed for some cases I have a pk violation, which pk is a long from IdGen .

Here are some pieces of my code

```
public static class UniqueIdGenerator
	{
		private static IdGenerator? _generator;

		public static void Configure(int generatorId)
		{
			if (_generator != null)
				throw new InvalidOperationException();

			_generator = new IdGenerator(generatorId);
		}

		public static long CreateId() => _generator?.CreateId() ?? throw new InvalidOperationException();
	}
```

Then I register it in program.cs class

```
public class Program
	{
		public static void Main(string[] args)
                {
                       UniqueIdGenerator.Configure(0);
                       //bla bla bla
                }
         }
```

and for example, if I want to create a new customer I call the static method like

```
public async Task AddCustomer(AddCustomerRequest request)
{
    var customer = new Customer
    {
        Id = UniqueIdGenerator.CreateId(),
        Name = request.Name,
        Phone = request.Phone
        //etc
    }
    //bla bla bla
}
```
Now I have some logs like that 
_Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Customers'. Cannot insert duplicate key in object 'dbo.Customers'. The duplicate key value is (842512993898987520)._

 And the customer with id 842512993898987520 already exists.
 Is something wrong with my configuration of IdGen?
Thanks in advance!

**Comment by minhhungit** [comment]
I think you should use only 1 instance, I got this kind of issue before due to multi IIS worker
If you use multi instance, try to setup difference generatorID for your instances

**Comment by RobThree** [comment]
IdGen is meant to be used as singleton (or as transient with guaranteed unique generatorid). If you're getting duplicate ID's then you're most likely using multiple instances with the same generator id.

See #33 or #26 for example, 

Also see our fresh new addition: [FAQ](https://github.com/RobThree/IdGen/blob/master/README.md#faq)

**Comment by dimitkos** [comment]
Because it is not clear to me, do you mean for example in the first instance of microservice to use for example `UniqueIdGenerator.Configure(0);`
and in the second instance of the microservice a different int like
`UniqueIdGenerator.Configure(1);`
in the program.cs class?

**Comment by RobThree** [comment]
Yes; if you have multiple instances they each need their own GeneratorID; they don't "know" about eachothers existence (hence the 'uncoordinated' part*) and start generating ID's on their own. The only thing preventing collisions (duplicates) is each relying on having their own GeneratorId. But, if at all possible, I'd just use a singleton instance.

\* That coordination is what _you're_ supposed to do by either making sure each generator gets it's own GeneratorId _or_ by just using a single instance.
