### ISSUE TITLE
Creating ID for a specific point in past time

### ISSUE THREAD

**Issue by dtln820** [RobThree/IdGen#35]
If I want my epoch time to be Jan 1st, 2018. And I need the ID that'd be generated for Jan 24, 2018 00:00.

```
var ts = new MockTimeSource(24, TimeSpan.FromDays(1), new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc));
var idGenerator = new IdGenerator(0, new IdGeneratorOptions(timeSource: ts));
var id = idGenerator.CreateId()
```

Is that the right way to get the id for some date in the past?

```
var epochDT = new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc);
var msgDT = new DateTime(2018, 1, 24, 0, 0, 0, DateTimeKind.Utc);
TimeSpan diff = msgDT - epochDT;
var ts = new MockTimeSource((long)diff.TotalMilliseconds, TimeSpan.FromMilliseconds(1), new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc));
var idGenerator = new IdGenerator(0, new IdGeneratorOptions(timeSource: ts));

var ts2 = new MockTimeSource(23, TimeSpan.FromDays(1), new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc));
var idGenerator2 = new IdGenerator(0, new IdGeneratorOptions(timeSource: ts2));
```
For the example above results for ID are very different.
> "id1": 833492090, - From ms
> "id2": 96468992 - From days

What am I missing that causes such difference?

**Comment by RobThree** [comment]
What/where are `id1` and `id2` coming from? I don't see them in your code. I'll try and repro the issue and see what's going on.

**Comment by RobThree** [comment]
Hmmm, `833492090` seems incorrect. I'm getting `8334920908800000` in my first test:

```c#
class Program
{
    static void Main(string[] args)
    {
        var epoch = new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var time = new DateTime(2018, 1, 24, 0, 0, 0, DateTimeKind.Utc);
            
        var opt = new IdGeneratorOptions(timeSource: new TestTimeSource(epoch, TimeSpan.FromMilliseconds(1), time));
        var idgen = new IdGenerator(0, opt);

        var id = idgen.CreateId();
        var decoded = idgen.FromId(id);
    }
}

public class TestTimeSource : ITimeSource
{
    public DateTimeOffset Epoch { get; }
    public TimeSpan TickDuration { get; }

    public long GetTicks() => (_target - Epoch).Ticks / TickDuration.Ticks;

    private DateTime _target;
    public TestTimeSource(DateTime epoch, TimeSpan tickDuration, DateTime target)
    {
        Epoch = epoch;
        TickDuration = tickDuration;
        _target = target;
    }
}
```

**Comment by RobThree** [comment]
Next, using the (unchanged) [`MockTimeSource`](https://github.com/RobThree/IdGen/blob/5b8ac4ecc2af17506793d0c59208604dbdc5118a/IdGenTests/Mocks/MockTimeSource.cs):

```c#
var epoch = new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc);
var time = new DateTime(2018, 1, 24, 0, 0, 0, DateTimeKind.Utc);
var diff = (long)(time - epoch).TotalMilliseconds;

var opt = new IdGeneratorOptions(timeSource: new MockTimeSource(diff, TimeSpan.FromMilliseconds(1), epoch));
var idgen = new IdGenerator(0, opt);

var id = idgen.CreateId();
var decoded = idgen.FromId(id);
```

Still gives me `8334920908800000`.


Edit: D'oh. The [`MockTimeSource`](https://github.com/RobThree/IdGen/blob/5b8ac4ecc2af17506793d0c59208604dbdc5118a/IdGenTests/Mocks/MockTimeSource.cs) doesn't take the tickduration (nor the epoch) into consideration (hence: why it's only meant for testing purposes).

`96468992` is also correct, but that is for a tickduration of a day:

```c#
class Program
{
    static void Main(string[] args)
    {
        var epoch = new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            
        var opt = new IdGeneratorOptions(timeSource: new TestTimeSource(epoch, TimeSpan.FromDays(1), 23));
        var idgen = new IdGenerator(0, opt);

        var id = idgen.CreateId();
        var decoded = idgen.FromId(id);
    }
}

public class TestTimeSource : ITimeSource
{
    public DateTimeOffset Epoch { get; }
    public TimeSpan TickDuration { get; }

    public long GetTicks() => (_target - Epoch).Ticks / TickDuration.Ticks;

    private DateTime _target;
    public TestTimeSource(DateTime epoch, TimeSpan tickDuration, long current)
    {
        Epoch = epoch;
        TickDuration = tickDuration;
        _target = epoch.AddTicks(current * tickDuration.Ticks);
    }
}
```

**Comment by dtln820** [comment]
Ah, alright. So I should use something similar to TestTimeSource from example above. Got it. Will try it then with my implementation of ITimeSource interface. Thanks.

**Comment by RobThree** [comment]
I think the above `ITimeSource` is a good starting point. Just a tip: A tickduration of a day is... HUGE 😉 

I will change the `MockTimeSource` to be a more correct implementation of an `ITimeSource` though. Should clear up some confusion 👍

**Comment by dtln820** [comment]
Yeah, I'm planning to use tick duration - ms. I have a table with messages that have creation time, and I want for new messages main ID to be a snowflake, and for the old ones to generate this snowflake based on the created date, but I'll convert it to ms, to keep with the right tick duration.

**Comment by RobThree** [comment]
Ok, then I'll go ahead and close this issue. I'm currently on vacation; I'll try to 'fix' the MockTimeSource sometime after.
