### ISSUE TITLE
Drop support for netstandard 1.1

### ISSUE THREAD

**Issue by akoken** [RobThree/IdGen#38]
Hello,

Do you have any plan to discontinue support for netstandard 1.1 since it contains vulnerable nuget packages such as `System.Drawing.Common`, `System.Net.Http`, `System.Net.Security` ? I think that people shouldn't have any problem using netstandard 2.0 nowadays.

**Comment by RobThree** [comment]
I don't see how _other_ packages having issues or vulnerabilities affects IdGen? Why would I drop support for older versions when people may be still using it and we don't have any good reason to drop support for it?

**Comment by akoken** [comment]
Our docker image fails in security stage of CI/CD pipeline. Since IdGen is targeted as netstandard 1.1, .NET SDK appears to be fetching outdated nuget packages, as I previously mentioned.

![image](https://user-images.githubusercontent.com/2880254/209718134-31fab9f7-4cbb-4945-bcca-7f191596f430.png)

![image](https://user-images.githubusercontent.com/2880254/209717880-f5c2acaa-2500-4b39-8a8e-d9dafc031ac1.png)

I can understand why you don't want to drop support for net standard 1.x.  [It is a best practice](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) to include a .NET Standard 2.0 target even if a library also targets older .NET Standard versions.

`<TargetFrameworks>netstandard1.1;netstandard2.0</TargetFrameworks>`

If you include netstandard 2.0 at least, the projects which are targeted as .NET 6 or .NET 7 can take advantage of it .

**Comment by RobThree** [comment]
Well, then we have our solution; I was gonna propose _adding_ netstandard 2.0 so that's a deal then 👊

**Comment by RobThree** [comment]
And [done](https://www.nuget.org/packages/IdGen/3.0.3). Should be available for download any second now.

Thanks for the feedback and making me aware of this issue 👊

**Comment by akoken** [comment]
TBH I didn't expect that so fast :) Thank you @RobThree.
