### ISSUE TITLE
Non-generic IIdGenerator

### ISSUE THREAD

**Issue by glen-84** [RobThree/IdGen#39]
I'm curious why the `IIdGenerator` interface is generic – aren't the values always `long`?

Maybe there could be a non-generic interface using `long` internally?

**Comment by RobThree** [comment]
Currently there's only long; the idea is/was that maybe sometime in the future another type is added. I don't see that happening but you never know 😉

**Comment by glen-84** [comment]
It would be a bit neater to just inject `IIdGenerator`. 🙂

**Comment by RobThree** [comment]
Something something hindsight 20/20.

I can't change this without breaking everyone's code and, quite honestly, I don't see the problem.

**Comment by glen-84** [comment]
> I can't change this without breaking everyone's code and, quite honestly, I don't see the problem.

I'm not sure what the breaking change would be, `IdGenerator` could implement both `IIdGenerator` and `IIdGenerator<long>`, with the latter being deprecated.

Anyway, it's not critical, just a suggestion.

**Comment by RobThree** [comment]
> I'm not sure what the breaking change would be

Ah, I see. I meant that if I would _replace_ the interface things would break. But, yes, I could _add_ an interface. I just think it clutters the interfaces.
