### ISSUE TITLE
Invalid Tests?

### ISSUE THREAD

**Issue by simmotech** [RobThree/IdGen#4]
Thanks for this code - I am having a play now.

I (well Resharper) noticed a few of the unit tests are using ReferenceEquals incorrectly:
> Assert.ReferenceEquals(target1, target2);

 should be

> Assert.IsTrue(ReferenceEquals(target1, target2));

**Comment by RobThree** [comment]
What is the exact message/reason Resharper gives? Why would one be better than the other? Genuinely curious, I don't see the difference. Also: wouldn't it have to be `Assert.AreSame(...)` then (which I came across on a quick Google search)?

**Comment by simmotech** [comment]
ReferenceEquals() is not a method on Assert but the one on Object, so the line does the comparison but throws away the result therefore the test would pass even if the ReferenceEquals() returned false.

(Resharper showed "Assert." in grey with the message "Qualifier is redundant"; it also underlined "ReferenceEquals" with the message "Return value of pure method is not used")

**Comment by RobThree** [comment]
Ah, d'uh. Should've noticed that myself. Don't know what I was thinking. I'll fix it as soon as I can (currently away from a decent computer). A PR is welcome too; keep it limited to the suggested changes and I'll merge ASAP.
