### ISSUE TITLE
Tag 3.0.3 is missing

### ISSUE THREAD

**Issue by rmandvikar** [RobThree/IdGen#44]
[Nuget 3.0.3](https://www.nuget.org/packages/IdGen/3.0.3) is out, but the git tag is missing in github repo ([see](https://github.com/RobThree/IdGen/tags)), and so is the release ([see](https://github.com/RobThree/IdGen/releases)). The nuget doesn't follow semver2 (with commit hash stamped) so I can't tell which commit I should be looking at. Please push the 3.0.3 version's tag to github. 

I _think_ this is the diff, but I can't be sure: 
https://github.com/RobThree/IdGen/compare/3.0.2..0ef2be36db0489d246fde51b51ad27056978d83b

**Comment by RobThree** [comment]
Done
