### ISSUE TITLE
NetStandard 2.0 support

### ISSUE THREAD

**Issue by bitcldr** [RobThree/IdGen#5]
Do you plan to release NuGet package with NetStandard 2.0 support?

**Comment by RobThree** [comment]
Yes; as soon as I get around to it.

**Comment by dotnetchris** [comment]
There's also https://github.com/joshclark/Flakey which maybe these projects can be un-forked with NS2.0

**Comment by RobThree** [comment]
Should work with [2.0.2](https://www.nuget.org/packages/IdGen/2.0.2)
