### ISSUE TITLE
Could we log how often we overflow sequence IDs and have to spinwait?

### ISSUE THREAD

**Issue by kimsey0** [RobThree/IdGen#54]
Somewhat related to #53, we would like to use `SequenceOverflowStrategy.SpinWait`, but to know how often we overflow the sequence number and have to spinwait. We could perhaps extract the sequence number from the returned ID and looks for those just before an overflow, but would it be possible for IdGen to somehow indicate that an overflow has happened? Maybe it's a bit much to integrate logging just for this, but perhaps there's be another way to do the signaling?

**Comment by RobThree** [comment]
I can imagine an event being raised or a 'overflowhandler' being passed to the ctor, but that's not something that'll make it into this version. Maybe next one. Meanwhile I suggest forking and adding the functionality to your own wishes / requirements.

See [my comment](https://github.com/RobThree/IdGen/issues/53#issuecomment-1609730849) in #53
