### ISSUE TITLE
Concurrency issues with instances scale up 

### ISSUE THREAD

**Issue by binraider** [RobThree/IdGen#55]
This is a question rather than an issue. Sorry about that. I want to use idGen for database table id generation in an app running on Fargate, or perhaps azure webapps. Given that the scaled out instances would use the same database is there a likelihood that there will be collisions when the apps or containers scale out (aspin up more fargate instances/webapp instances)? Would i have to somehow assign a different generator id for each appinstance as it starts up ? What would you do to ensure smooth id assignment in this scenario?

**Comment by RobThree** [comment]
> Given that the scaled out instances would use the same database is there a likelihood that there will be collisions when the apps or containers scale out

Very likely if not used correctly. See the [documentation](https://github.com/RobThree/IdGen#readme):

> _The generator-id-part of the Id is the part that you 'configure'; it could correspond to a host, thread, datacenter or continent: it's up to you. However, the generator-id should be unique in the system: if you have several hosts or threads generating Id's, each host or thread should have it's own generator-id. This could be based on the hostname, a config-file value or even be retrieved from an coordinating service. Remember: a generator-id should be unique within the entire system to avoid collisions!_

> Would i have to somehow assign a different generator id for each appinstance as it starts up ?

Exactly; that's exactly what the generator-id is for. See the above quote from the documentation.

> What would you do to ensure smooth id assignment in this scenario?

That's entirely up to you and depends on your requirements. Also explained in the documentation: "This library provides a basis for Id generation; **it does not provide [...] generator-id ('worker-id') coordination**."

**Comment by binraider** [comment]
Thanks. :)
