### ISSUE TITLE
Use dependabot to keep references up to date

### ISSUE THREAD

**Issue by tiksn** [RobThree/IdGen#56]
`IdGen.DependencyInjection` package referencing old `IdGen` and other old packages.

`dependabot` can help with that.

[Here](https://github.com/tiksn/TIKSN-Framework/blob/develop/.github/dependabot.yml) is one of my repos using [dependabot](https://github.com/dependabot)

**Comment by RobThree** [comment]
Fixed since packages are now released in tandem.
